lavalink:
  plugins:
    # - dependency: com.github.appujet:jiosaavn-plugin:1.0.2
    #   repository: https://jitpack.io
    # - dependency: com.dunctebot:skybot-lavalink-plugin:1.7.0
    #   snapshot: false
    - dependency: com.github.topi314.sponsorblock:sponsorblock-plugin:3.0.1
      snapshot: false
    - dependency: "dev.lavalink.youtube:youtube-plugin:c358ae412eeae61f87b6f99acfa57e8b91cc9218"
      snapshot: true # Set to true if you want to use a snapshot version.
    # - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.3.0"
    #   repository: "https://maven.lavalink.dev/releases" # this is optional for lavalink v4.0.0-beta.5 or greater
    #   snapshot: false # set to true if you want to use snapshot builds (see below)

  pluginsDir: ./plugins
  server:
    bufferDurationMs: 400
    filters:
      channelMix: true
      distortion: true
      equalizer: true
      karaoke: true
      lowPass: true
      rotation: true
      timescale: true
      tremolo: true
      vibrato: true
      volume: true
    frameBufferDurationMs: 5000
    gc-warnings: true
    opusEncodingQuality: 10
    password: ninju@lavalink
    playerUpdateInterval: 5
    resamplingQuality: HIGH
    soundcloudSearchEnabled: true
    sources:
      bandcamp: true
      http: true
      local: false
      mixer: true
      nico: true
      soundcloud: true
      twitch: true
      vimeo: true
      youtube: false
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
logging:
  file:
    path: ./logs/
  level:
    com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: DEBUG
    dev.lavalink.youtube: DEBUG
    lavalink: DEBUG
    lavalink.server.io.SocketContext: TRACE
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
  request:
    enabled: true
    includeClientInfo: true
    includeHeaders: false
    includePayload: true
    includeQueryString: true
    maxPayloadLength: 10000
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
plugins:
  #   lavasrc:
  #     providers:
  #       - dzisrc:"%ISRC%"
  #       - dzsearch:%QUERY%
  #       - jssearch:%QUERY%
  #       - scsearch:%QUERY%
  #       - tdsearch:%QUERY%
  #       - bcsearch:%QUERY%
  #     sources:
  #       applemusic: false
  #       deezer: false
  #       flowerytts: false
  #       spotify: true
  #       tidal: false
  #       yandexmusic: false
  #       youtube: false
  #     spotify:
  #       albumLoadLimit: 6
  #       countryCode: US
  #       playlistLoadLimit: 6
  #     youtube:
  #       countryCode: US
  youtube:
    allowDirectPlaylistIds: true
    allowDirectVideoIds: true
    allowSearch: true
    clients:
      - MUSIC
      - WEB
      - ANDROID_VR
      - WEBEMBEDDED
      - ANDROID_MUSIC
      #- ANDROID   its broken in main branch
      - IOS
      - MEDIA_CONNECT
      #- ANDROID_TESTSUITE   ded
      - TVHTML5EMBEDDED
      #- ANDROID_LITE  ded
    enabled: true
    pot:
      token: ${YOUTUBE_POT_TOKEN}
      visitorData: ${YOUTUBE_POT_VISITOR_DATA}
server:
  address: 0.0.0.0
  http2:
    enabled: false
  port: 6951
